=== soukupj00/bi-mdf/xml/schema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           xmlns:ex="http://example.org/xsd"
           xmlns:xml="http://www.w3.org/XML/1998/namespace"
           targetNamespace="http://example.org/xsd"
           elementFormDefault="qualified"
>
    <xs:element name="databazeFitnessCenter">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="ex:adresa" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element ref="ex:fitnessCentrum" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element ref="ex:clen" minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="adresa">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="iri" type="xs:anyURI"/>
                <xs:element name="mestoAdresa" xml:lang="cs" type="xs:string"/>
                <xs:element name="uliceAdresa" xml:lang="cs" type="xs:string"/>
                <xs:element name="pscAdresa" type="xs:integer"/>
                <xs:element name="cisloPopisneAdresa" type="xs:integer"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="fitnessCentrum">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="iri" type="xs:anyURI"/>
                <xs:element name="nazevFitnessCentrum" xml:lang="cs" type="xs:string"/>
                <xs:element name="kapacitaFitnessCentrum" type="xs:positiveInteger"/>
                <xs:element ref="ex:adresa" minOccurs="1" maxOccurs="1"/>
                <xs:sequence>
                    <xs:element name="maClena" minOccurs="0" maxOccurs="unbounded">
                        <xs:complexType>
                            <xs:attribute name="clenUri" type="xs:anyURI" />
                        </xs:complexType>
                    </xs:element>
                </xs:sequence>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="clen">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="iri" type="xs:anyURI"/>
                <xs:element name="jmenoClen" xml:lang="cs" type="xs:string"/>
                <xs:element name="osobniCisloClen" type="xs:positiveInteger"/>
                <xs:sequence>
                    <xs:element name="email" xml:lang="cs" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
                </xs:sequence>
                <xs:sequence>
                    <xs:element name="jeClenem" minOccurs="1" maxOccurs="unbounded">
                        <xs:complexType>
                            <xs:attribute name="fitnessCentrumUri" type="xs:anyURI" use="required"/>
                        </xs:complexType>
                    </xs:element>
                </xs:sequence>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== soukupj00/bi-mdf/xml/data.xml
<?xml version="1.0" encoding="UTF-8"?>
<databazeFitnessCenter xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                       xsi:schemaLocation="http://example.org/xml schema.xsd"
                       xmlns="http://example.org/xsd">

    <!-- Fitness centra -->
    <fitnessCentrum>
        <iri>https://example.org/fitnessCentrum/beastFitness</iri>
        <nazevFitnessCentrum>Beast Fitness</nazevFitnessCentrum>
        <kapacitaFitnessCentrum>300</kapacitaFitnessCentrum>
        <adresa>
            <iri>https://example.org/adresa/praha1</iri>
            <mestoAdresa>Praha</mestoAdresa>
            <uliceAdresa>Hradecká</uliceAdresa>
            <pscAdresa>10001</pscAdresa>
            <cisloPopisneAdresa>99</cisloPopisneAdresa>
        </adresa>
        <maClena clenUri="https://example.org/clen/Radek"/>
        <maClena clenUri="https://example.org/clen/Pepa"/>
        <maClena clenUri="https://example.org/clen/Eva"/>
    </fitnessCentrum>
    <fitnessCentrum>
        <iri>https://example.org/fitnessCentrum/olympiaFitness</iri>
        <nazevFitnessCentrum>Olympia Fitness</nazevFitnessCentrum>
        <kapacitaFitnessCentrum>400</kapacitaFitnessCentrum>
        <adresa>
            <iri>https://example.org/adresa/praha2</iri>
            <mestoAdresa>Praha</mestoAdresa>
            <uliceAdresa>Pražská</uliceAdresa>
            <pscAdresa>10099</pscAdresa>
            <cisloPopisneAdresa>876</cisloPopisneAdresa>
        </adresa>
        <maClena clenUri="https://example.org/clen/Pepa"/>
        <maClena clenUri="https://example.org/clen/Kuba"/>
        <maClena clenUri="https://example.org/clen/Eva"/>
        <maClena clenUri="https://example.org/clen/Milos"/>
    </fitnessCentrum>
    <fitnessCentrum>
        <iri>https://example.org/fitnessCentrum/strongGym</iri>
        <nazevFitnessCentrum>Strongman Gym HK</nazevFitnessCentrum>
        <kapacitaFitnessCentrum>150</kapacitaFitnessCentrum>
        <adresa>
            <iri>https://example.org/adresa/hradec</iri>
            <mestoAdresa>Hradec Králové</mestoAdresa>
            <uliceAdresa>Nádražní</uliceAdresa>
            <pscAdresa>55506</pscAdresa>
            <cisloPopisneAdresa>1123</cisloPopisneAdresa>
        </adresa>
        <maClena clenUri="https://example.org/clen/Pepa"/>
        <maClena clenUri="https://example.org/clen/David"/>
    </fitnessCentrum>
    <fitnessCentrum>
        <iri>https://example.org/fitnessCentrum/powerliftingGym</iri>
        <nazevFitnessCentrum>Powerlifting Club Pardubice</nazevFitnessCentrum>
        <kapacitaFitnessCentrum>50</kapacitaFitnessCentrum>
        <adresa>
            <iri>https://example.org/adresa/pardubice</iri>
            <mestoAdresa>Pardubice</mestoAdresa>
            <uliceAdresa>Pardubická</uliceAdresa>
            <pscAdresa>50802</pscAdresa>
            <cisloPopisneAdresa>9623</cisloPopisneAdresa>
        </adresa>
        <maClena clenUri="https://example.org/clen/Pepa"/>
        <maClena clenUri="https://example.org/clen/Milos"/>
    </fitnessCentrum>

    <!-- Clenove -->
    <clen>
        <iri>https://example.org/clen/Radek</iri>
        <jmenoClen>Radek Pospisil</jmenoClen>
        <osobniCisloClen>123456123</osobniCisloClen>
        <jeClenem fitnessCentrumUri="https://example.org/fitnessCentrum/beastFitness"/>
    </clen>
    <clen>
        <iri>https://example.org/clen/Pepa</iri>
        <jmenoClen>Josef Novák</jmenoClen>
        <osobniCisloClen>999888764</osobniCisloClen>
        <email>novak@seznam.cz</email>
        <email>pepa.novak.2@gmail.com</email>
        <jeClenem fitnessCentrumUri="https://example.org/fitnessCentrum/beastFitness"/>
        <jeClenem fitnessCentrumUri="https://example.org/fitnessCentrum/olympiaFitness"/>
        <jeClenem fitnessCentrumUri="https://example.org/fitnessCentrum/strongGym"/>
        <jeClenem fitnessCentrumUri="https://example.org/fitnessCentrum/powerliftingGym"/>
    </clen>
    <clen>
        <iri>https://example.org/clen/David</iri>
        <jmenoClen>David Hrdý</jmenoClen>
        <osobniCisloClen>123456789</osobniCisloClen>
        <email>hrdý@email.cz</email>
        <jeClenem fitnessCentrumUri="https://example.org/fitnessCentrum/strongGym"/>
    </clen>
    <clen>
        <iri>https://example.org/clen/Kuba</iri>
        <jmenoClen>Jakub Polévka</jmenoClen>
        <osobniCisloClen>6565656565</osobniCisloClen>
        <email>polevka@test.cz</email>
        <jeClenem fitnessCentrumUri="https://example.org/fitnessCentrum/olympiaFitness"/>
    </clen>
    <clen>
        <iri>https://example.org/clen/Eva</iri>
        <jmenoClen>Eva Morávková</jmenoClen>
        <osobniCisloClen>876876876</osobniCisloClen>
        <email>eva.m@test.cz</email>
        <jeClenem fitnessCentrumUri="https://example.org/fitnessCentrum/beastFitness"/>
        <jeClenem fitnessCentrumUri="https://example.org/fitnessCentrum/olympiaFitness"/>
    </clen>
    <clen>
        <iri>https://example.org/clen/Milos</iri>
        <jmenoClen>Miloš Nový</jmenoClen>
        <osobniCisloClen>999111999</osobniCisloClen>
        <email>minovym@test.cz</email>
        <jeClenem fitnessCentrumUri="https://example.org/fitnessCentrum/olympiaFitness"/>
        <jeClenem fitnessCentrumUri="https://example.org/fitnessCentrum/powerliftingGym"/>
    </clen>
</databazeFitnessCenter>
